//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Purview { get; set; }
        public string LastLoginIP { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<System.DateTime> LastLogoutTime { get; set; }
        public Nullable<int> LoginTimes { get; set; }
        public Nullable<int> AdminPurview_Article { get; set; }
        public Nullable<int> AdminPurview_Soft { get; set; }
        public Nullable<int> AdminPurview_Photo { get; set; }
        public string AdminPurview_Guest { get; set; }
        public string AdminPurview_Others { get; set; }
        public string RndPassword { get; set; }
    }
}
