//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cdelinknews
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<bool> Highlight { get; set; }
        public string Content { get; set; }
        public string Summary { get; set; }
        public string PageKeywords { get; set; }
        public Nullable<int> BigClassID { get; set; }
        public Nullable<int> SmallClassID { get; set; }
        public string BigClassName { get; set; }
        public string BigClassNumber { get; set; }
        public string SmallClassName { get; set; }
        public string SmallClassNumber { get; set; }
        public string FirstImageName { get; set; }
        public Nullable<int> ArticleSource { get; set; }
        public string User { get; set; }
        public string QtUser { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<bool> IsLogin { get; set; }
        public Nullable<byte> UserType { get; set; }
        public Nullable<int> Hits { get; set; }
        public bool Ok { get; set; }
        public Nullable<bool> Recommended { get; set; }
        public Nullable<bool> IsCount { get; set; }
        public Nullable<bool> IsTop { get; set; }
        public string ArticleType { get; set; }
    }
}
