//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cdelink_Config
    {
        public int SetupID { get; set; }
        public string SiteICP { get; set; }
        public string SiteName { get; set; }
        public string SiteUrl { get; set; }
        public string SiteStyle { get; set; }
        public string SiteTitle { get; set; }
        public string SiteDesc { get; set; }
        public string SiteKeys { get; set; }
        public string CompName { get; set; }
        public string Customer { get; set; }
        public string UserEmail { get; set; }
        public string UserPhone { get; set; }
        public string UserAdd { get; set; }
        public string UserOicq { get; set; }
        public string UserCard { get; set; }
        public string WaterMark { get; set; }
        public string Settings { get; set; }
        public string ImagePath { get; set; }
        public string ThemeTitle { get; set; }
        public string SoftInfo { get; set; }
        public string UploadExt { get; set; }
        public Nullable<byte> SiteLang { get; set; }
        public string AboutInfo { get; set; }
        public string HelpInfo { get; set; }
        public string RegInfo { get; set; }
        public string SiteJpeg { get; set; }
        public string FilterStr { get; set; }
    }
}
