//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lawyer
    {
        public int ID { get; set; }
        public string sLawyerName { get; set; }
        public bool bSex { get; set; }
        public int iAges { get; set; }
        public string sPhone { get; set; }
        public string sJobAddress { get; set; }
        public string sExecutionNum { get; set; }
        public string sPicture { get; set; }
    }
}
