//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sxr
    {
        public int ID { get; set; }
        public Nullable<int> UserOrder { get; set; }
        public string RealName { get; set; }
        public string IDCard { get; set; }
        public string CaseNum { get; set; }
        public string CaseBiaodi { get; set; }
        public string Adds { get; set; }
        public string UserPic { get; set; }
        public Nullable<bool> UserState { get; set; }
    }
}
