//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tj_Room
    {
        public int ID { get; set; }
        public Nullable<int> RoomOrder { get; set; }
        public string RoomName { get; set; }
        public Nullable<bool> RoomState { get; set; }
        public string RoomPic { get; set; }
    }
}
