//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserComment
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string PJType { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public string caseTypes { get; set; }
        public string Mobile { get; set; }
    }
}
