//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aboutuszxb> Aboutuszxb { get; set; }
        public virtual DbSet<AdminMessage> AdminMessage { get; set; }
        public virtual DbSet<Cdelinknews> Cdelinknews { get; set; }
        public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<Laws> Laws { get; set; }
        public virtual DbSet<LawsCase> LawsCase { get; set; }
        public virtual DbSet<Sxr> Sxr { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tj_Room> Tj_Room { get; set; }
        public virtual DbSet<TjCase> TjCase { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserComment> UserComment { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<BigClass_Dept> BigClass_Dept { get; set; }
        public virtual DbSet<BigClass_New> BigClass_New { get; set; }
        public virtual DbSet<Cdelink_Config> Cdelink_Config { get; set; }
        public virtual DbSet<SmallClass_Article> SmallClass_Article { get; set; }
    }
}
